### PR TITLE
Adding Message Count widgets

### PR DESCRIPTION
**Pull request by linda-baker**
These changes improve the appearance of metrics on the conflict visualizer page. New widgets allow users to view message counts on a configurable time range and see the past 7 days' trends. A few bugfixes improve visualization of assessment cards when little data is available.
image

### CODE REVIEW

**Comment by jacob6838** [comment]
I get a client side exception when running this PR with no data in MongoDB
image

**Comment by jacob6838** [comment]
Selecting no intersection, I still see BSM counts
image

**Comment by linda-baker** [comment]
> Selecting no intersection, I still see BSM counts image

I've been making some bugfixes for your other comment this morning, but I have no clue why this one is happening. @John-Wiens, why would querying BSM count with no intersection ID specified have different behavior than querying SPAT or MAP count with no intersection ID specified?

**Comment by John-Wiens** [comment]
Looks good
image

**Review by John-Wiens — APPROVED** [review]

**Pull request merged**
